### ISSUE TITLE
ColorPallette.js gives 404

### ISSUE THREAD

**Issue by tomaszmadeyski** [jacobjones/DoubleJay.Epi.ConfigurableColorPicker#1]
I've installed your package via Nuget, I've added `ColorPalette.config file` and added a field to my model as described in the doc.

Now, when I try to get page with IColor field in EditMode I get this in console:
![image](https://user-images.githubusercontent.com/1555694/56035530-b77ddf00-5d2a-11e9-9ed7-1e143b5f539c.png)

And page fails to load/render

**Comment by jacobjones** [comment]
Hi,

Thanks for raising this (and sorry it took so long for me to get to it). Basically you can resolve it by adding:

`
<add name="DoubleJay.Epi.ConfigurableColorPicker" />
`

to `protectedModules` it your web.config.

I've gone ahead and added a config transform and submitted a new version (1.0.1) to the Episerver NuGet feed—that should stop it happening going forward.
